{% set version = '0.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggpubr
  version: {{ version|replace("-", "_") }}

source:
  fn: ggpubr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggpubr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggpubr/ggpubr_{{ version }}.tar.gz
  sha256: 06c3075d8c452840662f5d041c3d966494b87254a52a858c849b9e1e96647766

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-cowplot
    - r-dplyr >=0.7.1
    - r-ggplot2
    - r-ggrepel
    - r-ggsci
    - r-ggsignif
    - r-glue
    - r-gridextra
    - r-magrittr
    - r-polynom
    - r-purrr
    - r-scales
    - r-tidyr
  run:
    - r-base
    - r-cowplot
    - r-dplyr >=0.7.1
    - r-ggplot2
    - r-ggrepel
    - r-ggsci
    - r-ggsignif
    - r-glue
    - r-gridextra
    - r-magrittr
    - r-polynom
    - r-purrr
    - r-scales
    - r-tidyr

test:
  commands:
    - $R -e "library('ggpubr')"           # [not win]
    - "\"%R%\" -e \"library('ggpubr')\""  # [win]

about:
  home: http://www.sthda.com/english/rpkgs/ggpubr
  license: GPL-2
  summary: The 'ggplot2' package is excellent and flexible for elegant data visualization in
    R. However the default generated plots requires some formatting before we can send
    them for publication. Furthermore, to customize a 'ggplot', the syntax is opaque
    and this raises the level of difficulty for researchers with no advanced R programming
    skills. 'ggpubr' provides some easy-to-use functions for creating and customizing
    'ggplot2'- based publication ready plots.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
